# Generated by Django 4.2.16 on 2025-08-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('src_dir', models.TextField(blank=True, help_text='the target source directory', primary_key=True, serialize=False)),
                ('run_dir', models.TextField(blank=True, help_text='the base directory of the execute path', null=True)),
                ('dest_dir', models.TextField(blank=True, help_text='the target destination directory', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('origin_path', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trimdocs.project')),
            ],
        ),
    ]
