# Generated by Django 4.2.16 on 2025-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme_filepath',
            field=models.TextField(blank=True, help_text='the path of the optional readme', null=True),
        ),
    ]
