# Generated by Django 4.2.16 on 2025-08-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimdocs', '0002_project_readme_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='origin_path_parent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
